<?php
/**
 * unit-test:/unit/form/index.phtml
 *
 * @creation  2018-05-16
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $form \OP\UNIT\Form */
?>
	<?php $form->Start() ?>
		<table id="testcase-form">
		<?php foreach( ['text','textarea','select','multiple','radio','checkbox','cookie','session','file'] as $name ): ?>
			<tr class="<?= $form->Validate($name) === false ? 'red':'' ?>">
				<th><?php $form->Label($name) ?></th><td><b>：</b></td>
				<td><?php $form->Input($name) ?></td>
				<td>
					<?php $form->Value($name) ?>
					<?php $form->Error($name) ?>
				</td>
			</tr>
		<?php endforeach; ?>
			<tr>
				<td colspan="4" style="text-align:center;">
					<!-- Submit button -->
					<button> Submit!! </button><br/>

					<!-- Clear button -->
					<button onclick="location.href='?clear=1'; return false;">
						Clear to form
					</button>

					<!-- Validation result -->
					<p class="<?= $form->Validate() ? 'blue':'red' ?>">Validation</p>
				</td>
			</tr>
		</table>
	<?php $form->Finish() ?>
<style>

FORM.OP td span:not(:last-child):after {
	content: ", ";
}

</style>
