<?php
/**
 * unit-test:/breadcrumb.phtml
 *
 * @creation  2019-01-16
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	...
$args = [];

//	...
echo '<div id="breadcrumb">'.PHP_EOL;

//	...
foreach( \App::Args() as $arg ){
	$args[] = $arg;
	$href = ConvertURL('testcase:/' . join('/', $args));
	printf('  <span><a href="%s">%s</a></span>'.PHP_EOL, $href, $arg);
};

//	...
echo '</div>'.PHP_EOL;

//	...
$args = App::Args();
$path = ConvertPath('testcase:/'.join('/', $args));
$href = ConvertURL($path);
$file = $path . '/action.php';

//	...
if(!file_exists($file) and is_dir($path) ){
	echo '<ol>'.PHP_EOL;
	foreach( scandir($path) as $file ){
		//	...
		list($name, $ext) = explode('.', $file.'.');

		//	...
		if( $ext !== 'php' or $file === 'index.php' ){
			continue;
		};

		//	...
		printf('  <li><a href="%s">%s</a></li>'.PHP_EOL, $href.$name, $name);
	};
	echo '</ol>'.PHP_EOL;
};
