<?php
/** op-module-testcase:/index-right-menu.phtml
 *
 * @created   2019-03-20
 * @version   1.0
 * @package   op-module-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

/* @var $app \OP\UNIT\App */
$root = RootPath('testcase');

?>

<!-- Breadcrumb navigation -->
<hr/>
<div class="breadcrumb-navigation">
	<span class="arg"><a href="<?= $root ?>">testcase</a></span>
	<?php
	$args = [];
	foreach( Args() as $arg ){
		$args[] = explode('.', $arg)[0];
		printf('<span class="arg"><a href="%s%s">%s</a></span>', $root, join('/',$args), $arg);
	}
	?>
</div>
<hr/>

<style>
.breadcrumb-navigation span,
.breadcrumb-navigation a {
	margin-left:  0.1em;
	margin-right: 0.1em;
}

.breadcrumb-navigation span:not(:last-child):after {
	margin-left:  0.4em;
	margin-right: 0.1em;
	content: ">";
}
</style>
