<?php
/**
 * unit-test:/index.phtml
 *
 * @creation  2018-04-17
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	...
$file = \OP\UNIT\NEWWORLD\Template::Args('file');
?>
<section id="testcase">
	<h1>TEST CASE</h1>
	<?php
	//	...
	App::Template('nav-right.phtml');

	//	...
	App::Template('breadcrumb.phtml');

	//	...
	if( $file ){
		App::Template($file);
	}else{
		//	...
		D( 'PHP version is ' . PHP_VERSION );

		//	...
		Html( ConvertPath('testcase:/') );
		Html( ConvertURL('testcase:/')  );
	}

	//	...
	if( $_GET['phpinfo'] ?? null ){
		phpinfo();
	};
	?>
</section>
