<?php
/** op-module-testcase:/index.phtml
 *
 * @created   2019-03-01
 * @version   1.0
 * @package   op-module-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

//	Check if http or shell.
if(!Env::isHttp() ){
	Template('controller.php');
	return;
}

/* @var $webpack UNIT\WebPack */
$webpack = Unit('WebPack');
$webpack->Css(__DIR__.'/menu');

?>
<section id="testcase">
<?php Template('index-right-menu.phtml') ?>
<?php Template('index-breadcrumb.phtml') ?>
<?php Template('controller.inc.php')     ?>
<?php Template('readme.inc.php')         ?>
</section>
<?php
//	...
echo '<hr/>'.PHP_EOL;

//	...
Html(null, 'hr');
Html( 'memory usage: ' . memory_get_usage() / 1000 .'KB (max: '. memory_get_peak_usage() / 1000 .'KB)');

//	...
$args = Args();

//	...
if( count($args) ){
	return;
}

//	...
Debug::Set('PHP' , PHP_VERSION);
Debug::Set('SAPI', php_sapi_name());
/*
Debug::Set('OP'  , Env::isLocalhost() ? 'localhost': geoip_country_code_by_name('onepiece-framework.com'));
*/
Debug::Set('test',true);
Debug::Set('test',false);
Debug::Set('test',null);
Debug::Set('test',Env::Timestamp());
Debug::Set('test',Env::Timestamp(1));
Debug::Out();
