<?php
/**
 * module-testcase:/index-right-menu.phtml
 *
 * @created   2019-03-20
 * @version   1.0
 * @package   module-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-03-20
 */
namespace OP;

/* @var $app UNIT\App */
$root = $app->URL('testcase:/');

//	...
$lists = [];

//	php, core, app
foreach( ['php','core','app'] as $cat ){
	//	...
	foreach( scandir( __DIR__.'/'.$cat ) as $file ){
		//	...
		$path = __DIR__."/{$cat}/$file";

		//	...
		if( is_dir($path) ){
			continue;
		}

		//	...
		list($name, $ext) = explode('.', $file);

		//	...
		if( $ext !== 'php' ){
			continue;
		}

		//	...
		if( $name === 'action' ){
			continue;
		}

		//	...
		$lists[$cat][$name] = ucfirst($name);
	}
}

//	unit
foreach( scandir( ConvertPath('asset:/unit/') ) as $file ){
	//	...
	if( $file[0] === '.' or $file[0] === '_' ){
		continue;
	}

	//	...
	$lists['unit'][$file] = ucfirst($file);
}

/* @var $app \OP\UNIT\App */
?>
<!-- Right float menu -->
<div class="testcase-right-float-menu">
	<ul>
		<?php foreach( $lists as $key => $list ): ?>
		<li>
			<a href="<?= "{$root}{$key}" ?>"><?= $key ?></a>
			<ul>
				<?php foreach( $list as $value => $label ): ?>
				<li><a href="<?= "{$root}{$key}/{$value}/" ?>"><?= $label ?></a></li>
				<?php endforeach; ?>
			</ul>
		</li>
		<?php endforeach; ?>
	</ul>
</div>
<style>
div.testcase-right-float-menu {
	float:   right;
	border:  1px solid black;
	margin:  0.5em 1em;
	padding: 0.5em 1em;
}

div.testcase-right-float-menu a {
	white-space: nowrap;
}
</style>
