<?php
/**
 * unit-test:/core/session.php
 *
 * @creation  2018-04-18
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section id="testcase">
	|
	<a href="?action=notice">Set notice</a> |
	<!--
	<a href="?action=app">Clear app session</a> |
	 -->
	<a href="?action=whole">Clear whole session</a> |
	<hr/>
</section>
