<?php
/**
 * unit-test:/unit/database/scaffold/action.phtml
 *
 * @creation  2018-06-10
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section id="testcase-scaffold">
<?php
/* @var $db \OP\UNIT\Database */
if( $db->isConnect() ){
	//	...
	App::Template('form-selector.phtml', ['form'=>$form, 'db'=>$db]);

	//	...
	App::Template('orm.phtml',['form'=>$form, 'db'=>$db]);

	//	...
	App::Template('selector.phtml', ['form'=>$form, 'db'=>$db]);
}else{
	//	...
	App::Template('form-login.phtml', ['form'=>$form]);
}
?>
</section>
<style>

#testcase-scaffold {
	_border: 1px solid black;
}

#testcase-scaffold div.record {
	_border: 1px solid black;
	float: left;
	margin-right:  1em;
	margin-bottom: 1em;
}

#record-area + * {
	clear: both;
}

</style>
