<?php
/**
 * unit-test:/unit/database/scaffold/orm.phtml
 *
 * @creation  2018-06-13
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $orm \OP\UNIT\ORM */
if(!$orm = Unit::Instance('ORM') ){
	return;
}

//	...
$pval = $_GET['pval'] ?? null;

//	...
$database = $form->GetValue('database');
$table    = $form->GetValue('table');

//	...
if( !$database or !$table ){
	return;
}

/* @var $db \OP\UNIT\Database */
$db->Database($database);

//	...
if( $table ){
	if(!$pkey = $db->Query("SHOW INDEX FROM {$database}.{$table}", 'show')['PRIMARY'][1]['Column_name'] ?? null ){
		throw new Exception("This table has not been set primary key. ({$database}.{$table})");
	}
}else{
	$pkey = $pval = null;
}

//	Join database object.
$orm->DB($db);

/* @var $record \OP\UNIT\ORM\Record */
if( $pkey and $pval ){
	//	Find single record by QQL. (QQL is "Quick Query Language")
	$record = $orm->Find("{$table}.{$pkey} = {$pval}");
}else{
	//	Generate Empty "Record" Object.
	$record = $orm->Create($table);
}

//	...
if(!$record->isReady() ){
	return;
}

//	...
$found = $record->isFound();
$valid = $record->isValid();

//	Generate form object.
$form = $record->Form();

//	Do validation.
if( $form->Validate() ){
	//	In case of new record, Set create datetime.
	if(!$found ){
		//	Generate created date time.
		$record->has('created') ? $record->Set('created', Time::GMT()) : null;
	}

	//	Save to database by Record object.
	$result = $orm->Save($record);

	//	if successful updated.
	if( $result and $found ){
		//	...
		$record->has('updated') ? $record->Set('updated', Time::GMT()) : null;

		//	...
		$orm->Save($record);
	}
}

?>
<hr/>
<?php $form->Start() ?>
<table id="testcase-scaffold-orm">
<?php foreach( $record->Column() as $field => $column ): ?>
	<?php if( $column['type'] === 'timestamp' ){ continue; } ?>
	<tr>
		<th><?= $form->Label($field) ?></th>
		<td><?= $form->Input($field) ?></td>
		<td><?= $form->Error($field) ?></td>
	</tr>
<?php endforeach; ?>
	<tr>
		<td colspan=3 class="text center">
			<?php if( null !== ($result ?? null) ): ?>
			<p class="i0 <?= $result ? 'success':'error' ?>" style="margin: 0.5em;">
				<?= $result ? 'Record was saved.':'There is no change to save.' ?>
			</p>
			<?php endif; ?>
			<button>
				<?= $found ? 'Update' : 'Create' ?>
			</button>
		</td>
	</tr>
</table>
<?php $form->Finish() ?>
<?php if(!$valid ){ $form->Debug(); } ?>
<style>

#testcase-scaffold-orm th {
	padding-right: 0.5em;
}

</style>
