<?php
/**
 * unit-test:/unit/database/scaffold/selector.phtml
 *
 * @creation  2018-06-11
 * @division  2018-06-13 from form-selector.phtml
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	Get database and table from form of selector.
$database = $form->GetValue('database');
$table    = $form->GetValue('table');

//	...
if( !$database or !$table ){
	return;
}

/* @var $pager \OP\UNIT\Pager */
$pager  = Unit::Instance('Pager');
$config = ['database'=>$database, 'table'=>$table];
$config = $pager->Config($config, $db);

//	...
if( empty($config['count']) ){
	return;
}

//	Display pagination at conditions.
echo '<hr/>';
$pager->Display();
echo '<hr/>';

//	Get primary field name.
$pkey = $db->Pkey($database, $table);

/* @var $db \OP\UNIT\Database */
printf('<div id="record-area">');
foreach( $db->Select($config) as $record ){
	printf('<div class="record">');
	printf('<a href="?%s">Edit of this record</a>', http_build_query( array_merge($_GET, ['pkey'=>$pkey,'pval'=>$record[$pkey]]) ));
	Json($record, '.OP_DUMP');
	printf('</div>');
}
printf('</div><br/>');

//	Display pagination at conditions.
echo '<hr/>';
$pager->Display();
echo '<hr/>';

//	...
App::WebPack('unit:/dump/dump.js');
App::WebPack('unit:/dump/dump.css');
