<?php
/**
 * unit-test:/unit/form/flow/conversion.phtml
 *
 * @creation  2018-05-23
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section id="testcase">
	<h2>Conversion</h2>
	<b>Count down <span id="count-down">5</span></b>
	<p>
		This is conversion page.
		This page is automatically transfer to thanks page.
		Please paste conversion script.
	</p>
</section>
<style>

#testcase p {
	border:  1px solid black;
	margin:  1em;
	padding: 1em;
}

</style>
<script>
document.addEventListener('DOMContentLoaded', function(){
	setInterval(function(){
		var count = document.getElementById('count-down').innerText;
		count--;
		if( count < 0 ){
			location.href = './thanks';
		}else{
			document.getElementById('count-down').innerText = count;
		}
	}, 1000);
}, false);
</script>
