<?php
/**
 * unit-test:/unit/form/flow/index.phtml
 *
 * @creation  2018-05-23
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $form \OP\UNIT\Form */
?>
<section id="testcase">
	<h2>Please input form</h2>
	<?php $form->Start(['action'=>'confirm']) ?>
		<table>
		<?php foreach( $form->Config()['input'] as $name => $input ): ?>
			<tr class="<?= $form->Validate($name) === false ? 'red':'' ?>">
				<th><?php $form->Label($name) ?></th><td><b> : </b></td>
				<td><?php $form->Input($name) ?></td>
				<td><?php $form->Error($name) ?></td>
			</tr>
		<?php endforeach; ?>
			<tr>
				<td></td><td></td>
				<td>
					<button>
						Submit this form
					</button>
					<br/>
					<button onclick="location.href='./clear'; return false;">
						Clear to form
					</button>
				</td>
				<td></td>
			</tr>
			<tr>
				<td></td><td></td>
				<td>
				</td>
				<td></td>
			</tr>
		</table>
	<?php $form->Finish() ?>

	<p class="<?= $form->Validate() ? 'blue':'red' ?>">Validation</p>

</section>
<style>

#testcase table tr td:nth-child(4) {
	padding-left: 0.5em;
}

#testcase table tr td:nth-child(4) > span {
	display: block;
}

#testcase table tr td:nth-child(4) > span:nth-child(2) {
	display: none;
}

</style>
