<?php
/**
 * unit-test:/unit/form/flow/thanks.phtml
 *
 * @creation  2018-05-23
 * @version   1.0
 * @package   unit-test
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $form \OP\UNIT\Form */
?>
<section id="testcase">
	<h2>Thank you for entry</h2>
	<p>This is thanks page.</p>
</section>
<style>

#testcase p {
	border:  1px solid black;
	margin:  1em;
	padding: 1em;
}

</style>
